
services:
  postgres:
    image: postgres:15-alpine
    container_name: projeto_integrador_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projeto_integrador
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/1_database.sql:ro
      - ./consulta.sql:/scripts/consulta.sql:ro

volumes:
  postgres-data:
    driver: local